#!/bin/bash

CHIPSET=$1
PRODUCT_NAME=$2
BUILD_ROOT_DIR=`pwd`

pack_non_hlos() {
    if [ "$PRODUCT_NAME" = "kobe" ]; then
        cd ./kobe/MSM"$CHIPSET".LA.2.0/common/build
        python build.py --nonhlos
    elif [ "$PRODUCT_NAME" = "aggassiz" ]; then
        cd ./aggassiz/MSM"$CHIPSET".LA.2.0/common/build
        python build.py --nonhlos
    elif [ "$PRODUCT_NAME" = "chopin" ]; then
        cd ./chopin/MSM"$CHIPSET".LA.2.0/common/build
        python build.py --nonhlos
    elif [ "$PRODUCT_NAME" = "bach" ]; then
        cd ./bach/MSM"$CHIPSET".LA.2.0/common/build
        python build.py --nonhlos
    fi

    cp ./bin/asic/NON-HLOS.bin $BUILD_ROOT_DIR/$PRODUCT_NAME/upgrade/
}

pack_non_hlos
